// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05XbCAHYEuvB6-eVzFO54SMbFt7oaRXM',
    appId: '1:258863536023:web:f75aeb3cd46fc86af556d2',
    messagingSenderId: '258863536023',
    projectId: 'kuicbuy',
    authDomain: 'kuicbuy.firebaseapp.com',
    storageBucket: 'kuicbuy.appspot.com',
    measurementId: 'G-6J2GEN26Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBjs4_rSungPcjmqKZFu_ihFxu1FCulQ4',
    appId: '1:258863536023:android:efa2b30e49279ceef556d2',
    messagingSenderId: '258863536023',
    projectId: 'kuicbuy',
    storageBucket: 'kuicbuy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pdfVT8kTmil8_b3EUrVB9C3C4Sbp11o',
    appId: '1:258863536023:ios:19595a83549fd1f1f556d2',
    messagingSenderId: '258863536023',
    projectId: 'kuicbuy',
    storageBucket: 'kuicbuy.appspot.com',
    iosBundleId: 'com.example.kuicbuy',
  );
}
